__version__ = "0.1.7"

from .ai import (
    ExecutionCache, WorkspaceMemory,
    adaptive_chunk_size, auto_benchmark, auto_select_backend,
    auto_select_preset, detect_available_backends, detect_hardware_profile,
    detect_join_keys, explain_pipeline, explain_step,
    geometry_repair_advice, get_execution_cache, list_registered_tools,
    natural_language_tool_runner, performance_warnings, plan_spatial_join,
    profile_dataset, prompt_to_report, quality_control_scan,
    query_local_model, recommend_crs, recommend_next_tool,
    recommend_parameters, register_tool, search_docs,
    suggest_duplicate_resolution, suggest_field_mapping,
    topology_validation_narrative, with_retry,
)
from .cartography import (
    BookmarkManager, LayerStyle,
    annotation_callouts, chart_distribution, chart_histogram,
    chart_scatter, chart_trend_line, comparison_view,
    export_map_image, graduated_symbol_renderer, heatmap_renderer,
    interactive_dashboard, label_features, load_style_template,
    map_series, print_layout, rule_based_renderer,
    save_style_template, story_map_html, unique_value_renderer,
)
from .compare import (benchmark_history_table, benchmark_summary_table,
                      build_comparison_report, correctness_summary_table,
                      export_benchmark_history, export_comparison_bundle,
                      render_benchmark_history_html, save_benchmark_snapshot)
from .crs import (
    auto_detect_coordinate_format, batch_coordinate_conversion_table,
    batch_project_features, best_projection_for_extent,
    compound_crs, convert_linear_units, coordinate_to_web_mercator,
    coordinate_to_wgs84, crs_aware_area, crs_aware_distance,
    crs_auto_detect, crs_comparison_report, crs_equal, crs_epsg_lookup,
    crs_from_authority, crs_from_epsg, crs_from_json, crs_from_prj_file,
    crs_from_proj, crs_from_user_input, crs_from_wkt, crs_to_json,
    crs_to_proj, crs_to_wkt, custom_crs_definition, define_projection,
    engineering_local_crs, geodesic_area_on_ellipsoid,
    geodesic_densify_line, geodesic_distance, geodesic_midpoint,
    geographic_to_projected, height_system_info, normalize_coordinate_order,
    parse_coordinate_text, parse_utm_coordinate, planetary_crs,
    polar_region_crs, project_on_the_fly, projected_to_geographic,
    resolve_crs_conflicts, rhumb_line_distance,
    state_plane_zone_auto_detect, utm_zone_for_lonlat,
    validate_crs_area_of_use, validate_crs_bounds, vertical_crs_from_epsg,
    vertical_transform, web_mercator_crs, xy_table_to_geographic_features,
)
from .data_management import (
    FieldDomain,
    append_records, archive_records, attach_media, batch_convert,
    batch_rename_fields, catalog_workspace, check_constraints,
    clean_coordinates, clone_metadata, copy_records, export_schema,
    export_zip_bundle, feature_change_report, field_calculate,
    import_zip_bundle, inspect_geodatabase, list_attachments,
    many_to_many_join, migration_plan, one_to_many_join,
    overwrite_records, read_metadata, read_parquet_filtered,
    reorder_fields, scaffold_project, schema_diff, snapshot_records,
    stamp_lineage, standardize_columns, truncate_records,
    upsert_records, validate_domains, write_excel_styled, write_metadata,
)
from .db import (
    read_duckdb, read_postgis, read_spatialite,
    write_duckdb, write_postgis, write_spatialite,
)
from .enterprise import (
    AuditLog, AuthProfile, ScheduledJob,
    deployment_template, feature_service_add, feature_service_delete,
    feature_service_query, feature_service_sync, feature_service_update,
    paginated_request, project_health_dashboard, publish_package,
    run_job_batch, share_item,
)
from .ecosystem import (
    build_workflow_wizard, deprecated_alias, get_migration_registry,
    get_plugin, get_recipe, list_plugins, list_recipes,
    recommend_recipes, register_migration, register_plugin,
    register_recipe, run_plugin, run_recipe,
)
from .equations import (accessibility_gini, age_adjusted_failure_rate, area_similarity,
                        composite_resilience_index, coordinate_distance,
                        corridor_strength, directional_alignment,
                        directional_bearing, euclidean_distance,
                        expected_outage_impact, exponential_decay,
                        gaussian_decay, gravity_interaction,
                        haversine_distance, logistic_service_probability,
                        prompt_decay, prompt_influence, prompt_interaction,
                        weighted_accessibility_score)
from .frame import Bounds, GeoPromptFrame, GeoPromptGeometryAccessor, GeoPromptSpatialIndex, GroupedGeoPromptFrame, groupedgeopromptframe, geopromptframe, geopromptspatialindex
from .geocoding import (
    TRAVEL_MODE_PRESETS,
    batch_forward_geocode, batch_reverse_geocode, fleet_routing_optimize,
    forward_geocode, get_travel_mode, intersection_lookup, parse_address,
    reverse_geocode, route_directions_narrative, route_milepost,
    standardize_address, stop_sequence_optimize, time_dependent_impedance,
)
from .geometry import (geometry_area, geometry_boundary, geometry_bounds,
                      geometry_centroid, geometry_centerline, geometry_concave_hull,
                      geometry_contains, geometry_convex_hull,
                      geometry_covered_by, geometry_covers, geometry_crosses,
                      geometry_delaunay, geometry_densify, geometry_disjoint,
                      geometry_distance, geometry_eliminate_slivers,
                      geometry_envelope, geometry_equals, geometry_erase,
                      geometry_from_bearing_distance, geometry_identity,
                      geometry_integrate, geometry_intersects,
                      geometry_intersects_bounds, geometry_is_empty,
                      geometry_linemerge, geometry_length, geometry_minimum_bounding,
                      geometry_multipart_to_singlepart, geometry_offset_curve,
                      geometry_overlaps, geometry_planarize, geometry_polygonize,
                      geometry_simplify, geometry_singlepart_to_multipart,
                      geometry_smooth, geometry_snap, geometry_split,
                      geometry_symmetric_difference, geometry_touches,
                      geometry_type, geometry_union, geometry_union_all,
                      geometry_validity_reason, geometry_vertices_to_points,
                      geometry_voronoi, geometry_within, geometry_within_bounds,
                      line_from_offsets, normalize_geometry, points_along_line,
                      repair_geometry, representative_point,
                      rotate_geometry, scale_geometry, skew_geometry,
                      split_line_at_point, transform_geometry,
                      translate_geometry, validate_geometry)
from .overlay import buffer_geometries, dissolve_geometries, geometry_from_shapely, geometry_to_geojson, geometry_to_shapely
from .io import (WORKLOAD_PRESETS, apply_field_aliases, apply_schema_mapping,
                 discover_layers, frame_to_geojson, generate_schema_migration_plan,
                 get_workload_preset,
                 iter_csv_points, iter_data,
                 iter_data_with_preset, read_cloud_json, read_csv_points, read_data, read_data_with_preset,
                 read_excel, read_features, read_geojson, read_geopackage,
                 read_geoparquet_metadata, read_points,
                 read_service_url, read_shapefile, read_table,
                 read_zipped_shapefile,
                 schema_report, validate_schema,
                 write_cloud_json, write_data, write_excel, write_geojson, write_geopackage,
                 write_geoparquet, write_shapefile)
from .interop import from_geopandas, geopandas_available, to_geopandas
from .raster import (inspect_raster, land_cover_summary, polygonize_raster,
                     raster_algebra, raster_build_overviews,
                     raster_change_detection, raster_chunk_process,
                     raster_class_breaks, raster_clip, raster_cog_info,
                     raster_cost_distance, raster_flow_accumulation,
                     raster_flow_direction, raster_hillshade,
                     raster_histogram, raster_lazy_algebra,
                     raster_least_cost_path, raster_mask, raster_mosaic,
                     raster_multidimensional_stack, raster_nodata_statistics,
                     raster_reproject, raster_report_card, raster_resample,
                     raster_segment, raster_slope_aspect,
                     raster_stream_extraction, raster_terrain_ruggedness,
                     raster_tile, raster_viewshed, raster_watershed,
                     rasterize_features, sample_raster_points,
                     write_raster, zonal_summary)
from .stats import (adaptive_kernel_density, catchment_analysis,
                    cluster_outlier_analysis, gearys_c,
                    geographically_weighted_summary, getis_ord_g,
                    hot_spot_analysis, idw_interpolation, kernel_density,
                    kriging_interpolation, local_morans_i, location_allocation,
                    morans_i, multi_criteria_decision_analysis,
                    neighborhood_statistics, od_matrix_optimization,
                    point_pattern_analysis, route_alternative_scoring,
                    scenario_comparison_engine, semivariogram, spatial_lag,
                    spatial_outliers, spatial_regression, spatial_weights_matrix,
                    spline_interpolation, suitability_model, territory_design,
                    trend_surface, zonal_statistics_by_class)
from .table import PromptTable, prompttable
from .temporal import (EventTracker, animation_frames,
                       asset_criticality_ranking, capital_planning_prioritize,
                       extract_z_values, failure_simulation_monte_carlo,
                       geometry_3d, geometry_3d_bounds,
                       resample_time_series, rolling_window_stats,
                       sort_by_time, surface_profile, surface_sample_grid,
                       temporal_join, temporal_window, voxel_grid)
from .topology import (feature_validation_pipeline, repair_suggestions,
                       snap_points, topology_diff_report, validate_topology_rules)
from .workspace import (GeoPromptWorkspace, JobSpec, LineageTracker,
                        build_workspace_manifest, export_provenance_bundle,
                        geopromptworkspace, jobspec, lineagetracker,
                        render_manifest_markdown)
from .viz import (BASEMAP_PRESETS, RESILIENCE_STYLE_PRESETS, SYMBOL_PRESETS,
                  before_after_comparison, plot_restoration_timeline,
                  plot_scenario_dashboard, plotly_scenario_dashboard,
                  portfolio_scorecard, quickplot, recommendation_card,
                  resilience_style_map, save_map,
                  save_plotly_html, to_choropleth, to_folium_map,
                  to_outage_overlay_map)
from .tools import (benchmark_function, bootstrap_confidence_interval,
                    build_multi_scenario_report,
                    build_resilience_portfolio_report,
                    build_resilience_summary_report,
                    build_scenario_report, calibrate_decay_parameters,
                    batch_accessibility_table,
                    compare_scenarios, export_scenario_report,
                    export_multi_scenario_report,
                    export_resilience_portfolio_report,
                    export_resilience_summary_report,
                    gravity_interaction_table,
                    multi_scenario_report_table,
                    monte_carlo_interval, normalize_units,
                    optimize_decay_parameters, sensitivity_analysis,
                    rank_scenarios,
                    scenario_report_table,
                    service_probability_table,
                    validate_numeric_series, vectorized_decay,
                    vectorized_gravity_interaction,
                    vectorized_service_probability,
                    batch_accessibility_scores)


__all__ = [
    "__version__",
    # --- ai ---
    "ExecutionCache",
    "WorkspaceMemory",
    "adaptive_chunk_size",
    "auto_benchmark",
    "auto_select_backend",
    "auto_select_preset",
    "detect_available_backends",
    "detect_hardware_profile",
    "detect_join_keys",
    "explain_pipeline",
    "explain_step",
    "geometry_repair_advice",
    "get_execution_cache",
    "list_registered_tools",
    "natural_language_tool_runner",
    "performance_warnings",
    "plan_spatial_join",
    "profile_dataset",
    "prompt_to_report",
    "quality_control_scan",
    "query_local_model",
    "recommend_crs",
    "recommend_next_tool",
    "recommend_parameters",
    "register_tool",
    "search_docs",
    "suggest_duplicate_resolution",
    "suggest_field_mapping",
    "topology_validation_narrative",
    "with_retry",
    # --- cartography ---
    "BookmarkManager",
    "LayerStyle",
    "annotation_callouts",
    "chart_distribution",
    "chart_histogram",
    "chart_scatter",
    "chart_trend_line",
    "comparison_view",
    "export_map_image",
    "graduated_symbol_renderer",
    "heatmap_renderer",
    "interactive_dashboard",
    "label_features",
    "load_style_template",
    "map_series",
    "print_layout",
    "rule_based_renderer",
    "save_style_template",
    "story_map_html",
    "unique_value_renderer",
    # --- compare ---
    "benchmark_history_table",
    "benchmark_summary_table",
    "build_comparison_report",
    "correctness_summary_table",
    "export_benchmark_history",
    "export_comparison_bundle",
    "render_benchmark_history_html",
    "save_benchmark_snapshot",
    # --- crs ---
    "auto_detect_coordinate_format",
    "batch_coordinate_conversion_table",
    "batch_project_features",
    "best_projection_for_extent",
    "compound_crs",
    "convert_linear_units",
    "coordinate_to_web_mercator",
    "coordinate_to_wgs84",
    "crs_aware_area",
    "crs_aware_distance",
    "crs_auto_detect",
    "crs_comparison_report",
    "crs_equal",
    "crs_epsg_lookup",
    "crs_from_authority",
    "crs_from_epsg",
    "crs_from_json",
    "crs_from_prj_file",
    "crs_from_proj",
    "crs_from_user_input",
    "crs_from_wkt",
    "crs_to_json",
    "crs_to_proj",
    "crs_to_wkt",
    "custom_crs_definition",
    "define_projection",
    "engineering_local_crs",
    "geodesic_area_on_ellipsoid",
    "geodesic_densify_line",
    "geodesic_distance",
    "geodesic_midpoint",
    "geographic_to_projected",
    "height_system_info",
    "normalize_coordinate_order",
    "parse_coordinate_text",
    "parse_utm_coordinate",
    "planetary_crs",
    "polar_region_crs",
    "project_on_the_fly",
    "projected_to_geographic",
    "resolve_crs_conflicts",
    "rhumb_line_distance",
    "state_plane_zone_auto_detect",
    "utm_zone_for_lonlat",
    "validate_crs_area_of_use",
    "validate_crs_bounds",
    "vertical_crs_from_epsg",
    "vertical_transform",
    "web_mercator_crs",
    "xy_table_to_geographic_features",
    # --- data_management ---
    "FieldDomain",
    "append_records",
    "archive_records",
    "attach_media",
    "batch_convert",
    "batch_rename_fields",
    "catalog_workspace",
    "check_constraints",
    "clean_coordinates",
    "clone_metadata",
    "copy_records",
    "export_schema",
    "export_zip_bundle",
    "feature_change_report",
    "field_calculate",
    "import_zip_bundle",
    "inspect_geodatabase",
    "list_attachments",
    "many_to_many_join",
    "migration_plan",
    "one_to_many_join",
    "overwrite_records",
    "read_metadata",
    "read_parquet_filtered",
    "reorder_fields",
    "scaffold_project",
    "schema_diff",
    "snapshot_records",
    "stamp_lineage",
    "standardize_columns",
    "truncate_records",
    "upsert_records",
    "validate_domains",
    "write_excel_styled",
    "write_metadata",
    # --- db ---
    "read_duckdb",
    "read_postgis",
    "read_spatialite",
    "write_duckdb",
    "write_postgis",
    "write_spatialite",
    # --- enterprise ---
    "AuditLog",
    "AuthProfile",
    "ScheduledJob",
    "deployment_template",
    "feature_service_add",
    "feature_service_delete",
    "feature_service_query",
    "feature_service_sync",
    "feature_service_update",
    "paginated_request",
    "project_health_dashboard",
    "publish_package",
    "run_job_batch",
    "share_item",
    # --- ecosystem ---
    "build_workflow_wizard",
    "deprecated_alias",
    "get_migration_registry",
    "get_plugin",
    "get_recipe",
    "list_plugins",
    "list_recipes",
    "recommend_recipes",
    "register_migration",
    "register_plugin",
    "register_recipe",
    "run_plugin",
    "run_recipe",
    # --- equations ---
    "accessibility_gini",
    "age_adjusted_failure_rate",
    "area_similarity",
    "composite_resilience_index",
    "coordinate_distance",
    "corridor_strength",
    "directional_alignment",
    "directional_bearing",
    "euclidean_distance",
    "expected_outage_impact",
    "exponential_decay",
    "gaussian_decay",
    "gravity_interaction",
    "haversine_distance",
    "logistic_service_probability",
    "prompt_decay",
    "prompt_influence",
    "prompt_interaction",
    "weighted_accessibility_score",
    # --- frame ---
    "Bounds",
    "GeoPromptFrame",
    "GeoPromptGeometryAccessor",
    "GeoPromptSpatialIndex",
    "GroupedGeoPromptFrame",
    "geopromptframe",
    "geopromptspatialindex",
    "groupedgeopromptframe",
    # --- geocoding ---
    "TRAVEL_MODE_PRESETS",
    "batch_forward_geocode",
    "batch_reverse_geocode",
    "fleet_routing_optimize",
    "forward_geocode",
    "get_travel_mode",
    "intersection_lookup",
    "parse_address",
    "reverse_geocode",
    "route_directions_narrative",
    "route_milepost",
    "standardize_address",
    "stop_sequence_optimize",
    "time_dependent_impedance",
    # --- geometry ---
    "geometry_area",
    "geometry_boundary",
    "geometry_bounds",
    "geometry_centerline",
    "geometry_centroid",
    "geometry_concave_hull",
    "geometry_contains",
    "geometry_convex_hull",
    "geometry_covered_by",
    "geometry_covers",
    "geometry_crosses",
    "geometry_delaunay",
    "geometry_densify",
    "geometry_disjoint",
    "geometry_distance",
    "geometry_eliminate_slivers",
    "geometry_envelope",
    "geometry_equals",
    "geometry_erase",
    "geometry_from_bearing_distance",
    "geometry_identity",
    "geometry_integrate",
    "geometry_intersects",
    "geometry_intersects_bounds",
    "geometry_is_empty",
    "geometry_length",
    "geometry_linemerge",
    "geometry_minimum_bounding",
    "geometry_multipart_to_singlepart",
    "geometry_offset_curve",
    "geometry_overlaps",
    "geometry_planarize",
    "geometry_polygonize",
    "geometry_simplify",
    "geometry_singlepart_to_multipart",
    "geometry_smooth",
    "geometry_snap",
    "geometry_split",
    "geometry_symmetric_difference",
    "geometry_touches",
    "geometry_type",
    "geometry_union",
    "geometry_union_all",
    "geometry_validity_reason",
    "geometry_vertices_to_points",
    "geometry_voronoi",
    "geometry_within",
    "geometry_within_bounds",
    "line_from_offsets",
    "normalize_geometry",
    "points_along_line",
    "repair_geometry",
    "representative_point",
    "rotate_geometry",
    "scale_geometry",
    "skew_geometry",
    "split_line_at_point",
    "transform_geometry",
    "translate_geometry",
    "validate_geometry",
    # --- interop ---
    "from_geopandas",
    "geopandas_available",
    "to_geopandas",
    # --- io ---
    "WORKLOAD_PRESETS",
    "apply_field_aliases",
    "apply_schema_mapping",
    "discover_layers",
    "frame_to_geojson",
    "generate_schema_migration_plan",
    "get_workload_preset",
    "iter_csv_points",
    "iter_data",
    "iter_data_with_preset",
    "read_cloud_json",
    "read_csv_points",
    "read_data",
    "read_data_with_preset",
    "read_excel",
    "read_features",
    "read_geojson",
    "read_geopackage",
    "read_geoparquet_metadata",
    "read_points",
    "read_service_url",
    "read_shapefile",
    "read_table",
    "read_zipped_shapefile",
    "schema_report",
    "validate_schema",
    "write_cloud_json",
    "write_data",
    "write_excel",
    "write_geojson",
    "write_geopackage",
    "write_geoparquet",
    "write_shapefile",
    # --- overlay ---
    "buffer_geometries",
    "dissolve_geometries",
    "geometry_from_shapely",
    "geometry_to_geojson",
    "geometry_to_shapely",
    # --- raster ---
    "inspect_raster",
    "land_cover_summary",
    "polygonize_raster",
    "raster_algebra",
    "raster_build_overviews",
    "raster_change_detection",
    "raster_chunk_process",
    "raster_class_breaks",
    "raster_clip",
    "raster_cog_info",
    "raster_cost_distance",
    "raster_flow_accumulation",
    "raster_flow_direction",
    "raster_hillshade",
    "raster_histogram",
    "raster_lazy_algebra",
    "raster_least_cost_path",
    "raster_mask",
    "raster_mosaic",
    "raster_multidimensional_stack",
    "raster_nodata_statistics",
    "raster_reproject",
    "raster_report_card",
    "raster_resample",
    "raster_segment",
    "raster_slope_aspect",
    "raster_stream_extraction",
    "raster_terrain_ruggedness",
    "raster_tile",
    "raster_viewshed",
    "raster_watershed",
    "rasterize_features",
    "sample_raster_points",
    "write_raster",
    "zonal_summary",
    # --- stats ---
    "adaptive_kernel_density",
    "catchment_analysis",
    "cluster_outlier_analysis",
    "gearys_c",
    "geographically_weighted_summary",
    "getis_ord_g",
    "hot_spot_analysis",
    "idw_interpolation",
    "kernel_density",
    "kriging_interpolation",
    "local_morans_i",
    "location_allocation",
    "morans_i",
    "multi_criteria_decision_analysis",
    "neighborhood_statistics",
    "od_matrix_optimization",
    "point_pattern_analysis",
    "route_alternative_scoring",
    "scenario_comparison_engine",
    "semivariogram",
    "spatial_lag",
    "spatial_outliers",
    "spatial_regression",
    "spatial_weights_matrix",
    "spline_interpolation",
    "suitability_model",
    "territory_design",
    "trend_surface",
    "zonal_statistics_by_class",
    # --- table ---
    "PromptTable",
    "prompttable",
    # --- temporal ---
    "EventTracker",
    "animation_frames",
    "asset_criticality_ranking",
    "capital_planning_prioritize",
    "extract_z_values",
    "failure_simulation_monte_carlo",
    "geometry_3d",
    "geometry_3d_bounds",
    "resample_time_series",
    "rolling_window_stats",
    "sort_by_time",
    "surface_profile",
    "surface_sample_grid",
    "temporal_join",
    "temporal_window",
    "voxel_grid",
    # --- tools ---
    "batch_accessibility_scores",
    "batch_accessibility_table",
    "benchmark_function",
    "bootstrap_confidence_interval",
    "build_multi_scenario_report",
    "build_resilience_portfolio_report",
    "build_resilience_summary_report",
    "build_scenario_report",
    "calibrate_decay_parameters",
    "compare_scenarios",
    "export_multi_scenario_report",
    "export_resilience_portfolio_report",
    "export_resilience_summary_report",
    "export_scenario_report",
    "gravity_interaction_table",
    "monte_carlo_interval",
    "multi_scenario_report_table",
    "normalize_units",
    "optimize_decay_parameters",
    "rank_scenarios",
    "scenario_report_table",
    "sensitivity_analysis",
    "service_probability_table",
    "validate_numeric_series",
    "vectorized_decay",
    "vectorized_gravity_interaction",
    "vectorized_service_probability",
    # --- topology ---
    "feature_validation_pipeline",
    "repair_suggestions",
    "snap_points",
    "topology_diff_report",
    "validate_topology_rules",
    # --- viz ---
    "BASEMAP_PRESETS",
    "RESILIENCE_STYLE_PRESETS",
    "SYMBOL_PRESETS",
    "before_after_comparison",
    "plot_restoration_timeline",
    "plot_scenario_dashboard",
    "plotly_scenario_dashboard",
    "portfolio_scorecard",
    "quickplot",
    "recommendation_card",
    "resilience_style_map",
    "save_map",
    "save_plotly_html",
    "to_choropleth",
    "to_folium_map",
    "to_outage_overlay_map",
    # --- workspace ---
    "GeoPromptWorkspace",
    "JobSpec",
    "LineageTracker",
    "build_workspace_manifest",
    "export_provenance_bundle",
    "geopromptworkspace",
    "jobspec",
    "lineagetracker",
    "render_manifest_markdown",
]